(() => {
  "use strict";

  const body = document.body;
  const root = document.documentElement;
  const page = body.dataset.page || "about";
  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  let lang = localStorage.getItem("hrbpa-lang") || "ru";
  if (!["ru", "uz", "en"].includes(lang)) lang = "ru";

  const shared = {
    ru: {
      menu: "Меню", about: "Об альянсе", residency: "Резидентство", journal: "Журнал", conferences: "Конференции", partners: "Партнёры", contacts: "Контакты", join: "Стать резидентом",
      addressShort: "Республика Узбекистан · Ташкент · 100085", joinText: "Приём заявок в резидентство открыт в течение всего года.", contactTitle: "Связаться", navigation: "Навигация", social: "Социальные сети", legal: "Правовая среда", lawSocial: "О социальном партнёрстве", lawEquality: "О равных правах и возможностях", lawNgo: "О негосударственных некоммерческих организациях", strategy: "Стратегия «Узбекистан — 2030»", partnerText: "Партнёр по мотивационному и кадровому консалтингу", dataTitle: "Данные и конфиденциальность", dataText: "На сайте нет рекламных и аналитических трекеров. В браузере локально сохраняется только выбранный язык интерфейса.", formText: "Формы передают только введённые вами данные через ваш почтовый клиент.", privacy: "Конфиденциальность", siteData: "Данные сайта", footerText: "HR Business Partners Association · Ташкент, Узбекистан", backHome: "На главную", discuss: "Обсудить сотрудничество", learnMore: "Подробнее", apply: "Оставить заявку"
    },
    uz: {
      menu: "Menyu", about: "Alyans haqida", residency: "Rezidentlik", journal: "Jurnal", conferences: "Konferensiyalar", partners: "Hamkorlar", contacts: "Bog‘lanish", join: "Rezident bo‘lish",
      addressShort: "O‘zbekiston Respublikasi · Toshkent · 100085", joinText: "Rezidentlikka arizalar yil davomida qabul qilinadi.", contactTitle: "Bog‘lanish", navigation: "Navigatsiya", social: "Ijtimoiy tarmoqlar", legal: "Huquqiy muhit", lawSocial: "Ijtimoiy sheriklik to‘g‘risida", lawEquality: "Teng huquq va imkoniyatlar kafolatlari to‘g‘risida", lawNgo: "Nodavlat notijorat tashkilotlari to‘g‘risida", strategy: "«O‘zbekiston — 2030» strategiyasi", partnerText: "Motivatsiya va kadrlar konsaltingi bo‘yicha hamkor", dataTitle: "Ma’lumotlar va maxfiylik", dataText: "Saytda reklama va analitika trekerlari yo‘q. Brauzerda faqat tanlangan interfeys tili saqlanadi.", formText: "Shakllar faqat siz kiritgan ma’lumotlarni elektron pochta dasturingiz orqali yuboradi.", privacy: "Maxfiylik", siteData: "Sayt ma’lumotlari", footerText: "HR Business Partners Association · Toshkent, O‘zbekiston", backHome: "Bosh sahifa", discuss: "Hamkorlikni muhokama qilish", learnMore: "Batafsil", apply: "Ariza qoldirish"
    },
    en: {
      menu: "Menu", about: "About", residency: "Residency", journal: "Journal", conferences: "Conferences", partners: "Partners", contacts: "Contacts", join: "Become a resident",
      addressShort: "Republic of Uzbekistan · Tashkent · 100085", joinText: "Residency applications are open throughout the year.", contactTitle: "Contact", navigation: "Navigation", social: "Social media", legal: "Legal framework", lawSocial: "On social partnership", lawEquality: "On guarantees of equal rights and opportunities", lawNgo: "On non-governmental non-profit organisations", strategy: "Uzbekistan — 2030 Strategy", partnerText: "Motivation and HR consulting partner", dataTitle: "Data and privacy", dataText: "The website uses no advertising or analytics trackers. Only the selected interface language is stored locally.", formText: "Forms transfer only the data you enter through your email client.", privacy: "Privacy", siteData: "Site data", footerText: "HR Business Partners Association · Tashkent, Uzbekistan", backHome: "Home", discuss: "Discuss a partnership", learnMore: "Learn more", apply: "Send an application"
    }
  };

  const pages = {
    about: {
      ru: {
        title: "Платформа делового доверия с 2023 года", lead: "HRBPA формирует новую культуру управления и человеческого капитала — через сильные связи, публичную экспертизу и совместные проекты.", kicker: "ОБ АЛЬЯНСЕ", stats: [["05 · 2023", "дата основания"], ["100+", "компаний-партнёров"], ["1000+", "проектов с 2014 года"]],
        trustTitle: "Доверие — измеримый бизнес-актив", trustLead: "Мы создаём среду, где репутация ускоряет решения, знания превращаются в партнёрства, а профессиональные связи работают на долгосрочный рост.", pillars: [["01", "Твёрдый капитал", "Доверие снижает транзакционные издержки и помогает быстрее переходить от знакомства к совместному действию."], ["02", "Глобальный масштаб", "На одной площадке встречаются лидеры бизнеса, государственные институты и международные эксперты."], ["03", "Устойчивый рост", "Сообщество поддерживает проекты, которые усиливают управленческую культуру и человеческий капитал."]],
        benefitsTitle: "Что получает участник альянса", benefits: [["Государственный диалог", "Прямой профессиональный контакт с институтами и отраслевыми площадками."], ["B2B-сетевой рост", "Новые деловые связи, коллаборации и вход в устойчивую партнёрскую сеть."], ["Медиа-присутствие", "Экспертные публикации, интервью и заметность на ресурсах BUSINESS HOLISTIC."], ["Институциональное доверие", "Репутационное соседство с лидерами рынка и проверенными экспертами."], ["Умный доступ", "Приоритет на закрытых встречах, конференциях и отраслевых обсуждениях."], ["Практикумы и решения", "Прикладные инструменты для реальных управленческих и HR-задач."]],
        timelineTitle: "Как формировалась орбита", timeline: [["2023", "Основание HRBPA и первая конференция в Hilton: 250 участников из пяти стран."], ["2024", "UNITE EVERYONE: 275 участников из 18 стран и запуск зонтичного бренда BUSINESS HOLISTIC Alliance."], ["2025", "Конференция «Доверие как основа успеха»: 29 спикеров и 327 участников из 13 стран."]],
        directionsTitle: "Три направления — одна экосистема", directions: [["Ассоциация", "Профессиональное сообщество, резидентство и B2B-связи."], ["BUSINESS HOLISTIC", "Научно-деловой журнал и площадка публичной экспертизы."], ["Конференция", "Ежегодный международный форум для бизнеса, государства и экспертов."]],
        founderTitle: "Инициатор и основатель", founderName: "Мадина Билалова", founderText: "Основатель BUSINESS HOLISTIC Alliance и HRBPA. Объединяет управленческую экспертизу, коммуникационные платформы и международные деловые связи."
      },
      uz: {
        title: "2023-yildan beri ishbilarmonlik ishonchi platformasi", lead: "HRBPA kuchli aloqalar, ommaviy ekspertiza va qo‘shma loyihalar orqali boshqaruv hamda inson kapitalining yangi madaniyatini shakllantiradi.", kicker: "ALYANS HAQIDA", stats: [["05 · 2023", "tashkil etilgan sana"], ["100+", "hamkor kompaniya"], ["1000+", "2014-yildan beri loyiha"]],
        trustTitle: "Ishonch — o‘lchanadigan biznes aktivi", trustLead: "Biz obro‘ qarorlarni tezlashtiradigan, bilim hamkorlikka aylanadigan va professional aloqalar uzoq muddatli o‘sishga xizmat qiladigan muhit yaratamiz.", pillars: [["01", "Mustahkam kapital", "Ishonch tranzaksiya xarajatlarini kamaytiradi va hamkorlikni tezlashtiradi."], ["02", "Global miqyos", "Biznes yetakchilari, davlat institutlari va xalqaro ekspertlar bir platformada uchrashadi."], ["03", "Barqaror o‘sish", "Hamjamiyat boshqaruv madaniyati va inson kapitalini kuchaytiradigan loyihalarni qo‘llab-quvvatlaydi."]],
        benefitsTitle: "Alyans ishtirokchisi nimalarga ega bo‘ladi", benefits: [["Davlat bilan muloqot", "Institutlar va soha platformalari bilan professional aloqa."], ["B2B tarmoq o‘sishi", "Yangi aloqalar, kollaboratsiyalar va barqaror hamkorlar tarmog‘i."], ["Media ishtiroki", "Ekspert nashrlari, intervyular va BUSINESS HOLISTIC resurslarida ko‘rinish."], ["Institutsional ishonch", "Bozor yetakchilari va tekshirilgan ekspertlar bilan obro‘li muhit."], ["Aqlli kirish", "Yopiq uchrashuvlar va konferensiyalarda ustuvorlik."], ["Amaliy yechimlar", "Real boshqaruv va HR vazifalari uchun vositalar."]],
        timelineTitle: "Orbita qanday shakllandi", timeline: [["2023", "HRBPA tashkil etildi va Hilton’da besh davlatdan 250 ishtirokchi qatnashgan ilk konferensiya o‘tkazildi."], ["2024", "UNITE EVERYONE: 18 davlatdan 275 ishtirokchi va BUSINESS HOLISTIC Alliance brendi ishga tushdi."], ["2025", "«Ishonch — muvaffaqiyat asosi»: 13 davlatdan 327 ishtirokchi va 29 spiker."]],
        directionsTitle: "Uch yo‘nalish — yagona ekotizim", directions: [["Assotsiatsiya", "Professional hamjamiyat, rezidentlik va B2B aloqalar."], ["BUSINESS HOLISTIC", "Ilmiy-ishbilarmonlik jurnali va ommaviy ekspertiza maydoni."], ["Konferensiya", "Biznes, davlat va ekspertlar uchun yillik xalqaro forum."]],
        founderTitle: "Tashabbuskor va asoschi", founderName: "Madina Bilalova", founderText: "BUSINESS HOLISTIC Alliance va HRBPA asoschisi. Boshqaruv ekspertizasi, kommunikatsiya platformalari va xalqaro biznes aloqalarini birlashtiradi."
      },
      en: {
        title: "A platform for business trust since 2023", lead: "HRBPA shapes a new culture of management and human capital through strong relationships, visible expertise and joint projects.", kicker: "ABOUT THE ALLIANCE", stats: [["05 · 2023", "founded"], ["100+", "partner companies"], ["1000+", "projects since 2014"]],
        trustTitle: "Trust is a measurable business asset", trustLead: "We create an environment where reputation accelerates decisions, knowledge turns into partnerships and professional ties support long-term growth.", pillars: [["01", "Hard capital", "Trust reduces transaction costs and shortens the path from introduction to joint action."], ["02", "Global scale", "Business leaders, public institutions and international experts meet on one platform."], ["03", "Sustainable growth", "The community supports projects that strengthen management culture and human capital."]],
        benefitsTitle: "What alliance members gain", benefits: [["Public-sector dialogue", "A professional line to institutions and industry platforms."], ["B2B network growth", "New connections, collaborations and entry into a durable partner network."], ["Media presence", "Expert publications, interviews and visibility across BUSINESS HOLISTIC."], ["Institutional trust", "Reputational proximity to market leaders and verified experts."], ["Smart access", "Priority at private meetings, conferences and industry discussions."], ["Workshops and solutions", "Practical tools for real management and HR challenges."]],
        timelineTitle: "How the orbit took shape", timeline: [["2023", "HRBPA was founded and held its first Hilton conference with 250 participants from five countries."], ["2024", "UNITE EVERYONE welcomed 275 participants from 18 countries and launched BUSINESS HOLISTIC Alliance."], ["2025", "Trust as the Foundation of Success: 29 speakers and 327 participants from 13 countries."]],
        directionsTitle: "Three directions, one ecosystem", directions: [["Association", "A professional community, residency and B2B relationships."], ["BUSINESS HOLISTIC", "A research and business journal and platform for visible expertise."], ["Conference", "An annual international forum for business, government and experts."]],
        founderTitle: "Initiator and founder", founderName: "Madina Bilalova", founderText: "Founder of BUSINESS HOLISTIC Alliance and HRBPA, connecting management expertise, communication platforms and international business relationships."
      }
    },
    residency: {
      ru: {
        kicker: "РЕЗИДЕНТСТВО", title: "Присутствие, которое превращается в влияние", lead: "Годовое участие открывает доступ к сообществу, публичной экспертизе, событиям и совместным инициативам HRBPA.", badge: "9 возможностей роста", groups: [["Доступ", [["Закрытые встречи", "Разговор по существу с лидерами рынка и приглашёнными экспертами."], ["Расширение контактов", "Деловая сеть без случайных знакомств и информационного шума."], ["Приоритет на событиях", "Ранний доступ и специальные условия на ключевых мероприятиях."]]], ["Видимость", [["Экспертное позиционирование", "Публичная роль в профессиональной повестке альянса."], ["Присутствие бренда", "Интеграция компании в площадки и коммуникации HRBPA."], ["Медиа-освещение", "Интервью, публикации и материалы BUSINESS HOLISTIC."]]], ["Развитие", [["Экспертная аналитика", "Доступ к разбору практик и актуальным бизнес-инсайтам."], ["Публикации в журнале", "Специальные условия на участие в BUSINESS HOLISTIC."], ["Партнёрские инициативы", "Возможность запускать совместные проекты внутри экосистемы."]]]],
        tiersTitle: "Выберите масштаб присутствия", tiers: [["SILVER", "$600", "18 БРВ", ["Закрытые профессиональные встречи", "Присутствие на ресурсах альянса", "Партнёрская сеть"]], ["GOLD", "$1000", "30 БРВ", ["Приоритет на ключевых событиях", "Экспертное позиционирование", "Информационное освещение"]], ["PLATINUM", "$1500", "45 БРВ", ["Максимальное присутствие бренда", "Партнёрские спецпроекты", "Публикации на особых условиях"]]], featured: "Главная орбита", perYear: "в год", choose: "Выбрать уровень",
        stepsTitle: "От заявки до активации", steps: [["01", "Заявка", "Вы обозначаете интерес и желаемый уровень участия."], ["02", "Разговор", "Секретариат уточняет задачи и формат взаимодействия."], ["03", "Соглашение", "Фиксируем условия участия на один год."], ["04", "Включение", "Команда активирует доступ и план совместных действий."]], ctaTitle: "Готовы войти в деловую орбиту?", ctaText: "Оставьте контакт — секретариат HRBPA свяжется с вами в течение рабочего дня."
      },
      uz: {
        kicker: "REZIDENTLIK", title: "Ta’sirga aylanadigan ishtirok", lead: "Yillik ishtirok HRBPA hamjamiyati, ommaviy ekspertiza, tadbirlar va qo‘shma tashabbuslarga kirish imkonini beradi.", badge: "9 ta o‘sish imkoniyati", groups: [["Kirish", [["Yopiq uchrashuvlar", "Bozor yetakchilari va taklif etilgan ekspertlar bilan mazmunli suhbat."], ["Aloqalarni kengaytirish", "Tasodifiy tanishuvlar va axborot shovqinisiz biznes tarmog‘i."], ["Tadbirlarda ustuvorlik", "Asosiy tadbirlarga erta kirish va maxsus shartlar."]]], ["Ko‘rinish", [["Ekspert pozitsiyasi", "Alyans professional kun tartibidagi ommaviy rol."], ["Brend ishtiroki", "Kompaniyani HRBPA platformalari va kommunikatsiyalariga integratsiya qilish."], ["Media yoritilishi", "BUSINESS HOLISTIC intervyu va nashrlari."]]], ["Rivojlanish", [["Ekspert tahlili", "Amaliyotlar tahlili va dolzarb biznes fikrlariga kirish."], ["Jurnalda nashr", "BUSINESS HOLISTIC’da ishtirok etish uchun maxsus shartlar."], ["Hamkorlik tashabbuslari", "Ekotizim doirasida qo‘shma loyihalarni boshlash imkoniyati."]]]],
        tiersTitle: "Ishtirok ko‘lamini tanlang", tiers: [["SILVER", "$600", "18 BHM", ["Yopiq professional uchrashuvlar", "Alyans resurslarida ishtirok", "Hamkorlar tarmog‘i"]], ["GOLD", "$1000", "30 BHM", ["Asosiy tadbirlarda ustuvorlik", "Ekspert pozitsiyasi", "Axborot yoritilishi"]], ["PLATINUM", "$1500", "45 BHM", ["Brendning maksimal ishtiroki", "Maxsus hamkorlik loyihalari", "Maxsus shartlarda nashrlar"]]], featured: "Asosiy orbita", perYear: "yiliga", choose: "Darajani tanlash",
        stepsTitle: "Arizadan faollashtirishgacha", steps: [["01", "Ariza", "Qiziqish va ishtirok darajasini ko‘rsatasiz."], ["02", "Suhbat", "Kotibiyat maqsad va hamkorlik formatini aniqlaydi."], ["03", "Kelishuv", "Bir yillik ishtirok shartlarini belgilaymiz."], ["04", "Qo‘shilish", "Jamoa kirish va birgalikdagi harakatlar rejasini faollashtiradi."]], ctaTitle: "Biznes orbitasiga kirishga tayyormisiz?", ctaText: "Kontaktingizni qoldiring — HRBPA kotibiyati bir ish kuni ichida bog‘lanadi."
      },
      en: {
        kicker: "RESIDENCY", title: "Presence that turns into influence", lead: "Annual participation opens access to the HRBPA community, visible expertise, events and joint initiatives.", badge: "9 growth opportunities", groups: [["Access", [["Private meetings", "Focused dialogue with market leaders and invited experts."], ["Expanded contacts", "A business network without random introductions or noise."], ["Event priority", "Early access and preferred terms for flagship events."]]], ["Visibility", [["Expert positioning", "A public role in the alliance’s professional agenda."], ["Brand presence", "Integration into HRBPA platforms and communications."], ["Media coverage", "Interviews, publications and BUSINESS HOLISTIC content."]]], ["Development", [["Expert analytics", "Access to practice reviews and current business insights."], ["Journal publications", "Preferred terms for BUSINESS HOLISTIC participation."], ["Partner initiatives", "The opportunity to launch joint projects inside the ecosystem."]]]],
        tiersTitle: "Choose your scale of presence", tiers: [["SILVER", "$600", "18 BRV", ["Private professional meetings", "Presence across alliance resources", "Partner network"]], ["GOLD", "$1000", "30 BRV", ["Priority at flagship events", "Expert positioning", "Media coverage"]], ["PLATINUM", "$1500", "45 BRV", ["Maximum brand presence", "Partner special projects", "Preferred publication terms"]]], featured: "Main orbit", perYear: "per year", choose: "Choose level",
        stepsTitle: "From application to activation", steps: [["01", "Application", "Tell us your interest and preferred level."], ["02", "Conversation", "The Secretariat clarifies your goals and format."], ["03", "Agreement", "We confirm the terms for one year."], ["04", "Activation", "The team opens access and a plan of joint actions."]], ctaTitle: "Ready to enter the business orbit?", ctaText: "Leave your details and the HRBPA Secretariat will contact you within one business day."
      }
    },
    journal: {
      ru: {
        kicker: "BUSINESS HOLISTIC JOURNAL", title: "Ваш опыт читают там, где принимают решения", lead: "Международный научно-деловой журнал с адресной дистрибуцией в VIP-вагонах, аэропортах, министерствах, посольствах и банках.", issue: "ВЫПУСК № 01", issueText: "Лидерская экспертиза, бизнес-кейсы и идеи, которые формируют деловую повестку Центральной Азии.", reserve: "Забронировать публикацию",
        formatsTitle: "Четыре формата присутствия", formats: [["01", "EXPERT COLUMN", "$300", "1 страница", ["Фотосессия лидера", "Работа журналиста", "Полная сеть дистрибуции"]], ["02", "SUCCESS STORY", "$550", "разворот", ["Глубинное интервью", "История бренда и 2–3 изображения", "Публикация на сайте и LinkedIn"]], ["03", "BUSINESS ECOSYSTEM", "$1000", "4 страницы", ["Личный бренд и кейс компании", "Командный портрет", "Видеоинтервью и Reels / Shorts"]], ["04", "COVER STAR", "$2500", "обложка + 6 страниц", ["Главное лицо выпуска", "Статус генерального партнёра", "Полное digital-продвижение"]]], selected: "Чаще выбирают",
        productionTitle: "Редакция берёт производство на себя", production: [["Выездная съёмка", "Команда организует визуальное производство на вашей площадке."], ["Журналист и перевод", "Интервью, редактура и адаптация на RU / UZ / EN."], ["Digital-форматы", "Материалы для портала, соцсетей и коротких видео."], ["VIP-дистрибуция", "Адресное распространение в деловой и институциональной среде."]],
        stepsTitle: "От идеи до выпуска", steps: [["01", "Выбор формата"], ["02", "Согласование концепции"], ["03", "Интервью и производство"], ["04", "Редактура и комплаенс"], ["05", "Печать, дистрибуция и digital-релиз"]]
      },
      uz: {
        kicker: "BUSINESS HOLISTIC JOURNAL", title: "Tajribangiz qarorlar qabul qilinadigan joyda o‘qiladi", lead: "VIP vagonlar, aeroportlar, vazirliklar, elchixonalar va banklarda manzilli tarqatiladigan xalqaro ilmiy-ishbilarmonlik jurnali.", issue: "№ 01 SON", issueText: "Markaziy Osiyo biznes kun tartibini shakllantiradigan yetakchilik ekspertizasi, biznes keyslar va g‘oyalar.", reserve: "Nashrni band qilish",
        formatsTitle: "Ishtirokning to‘rt formati", formats: [["01", "EXPERT COLUMN", "$300", "1 sahifa", ["Lider fotosessiyasi", "Jurnalist ishi", "To‘liq tarqatish tarmog‘i"]], ["02", "SUCCESS STORY", "$550", "2 sahifa", ["Chuqur intervyu", "Brend tarixi va 2–3 tasvir", "Sayt va LinkedIn’da nashr"]], ["03", "BUSINESS ECOSYSTEM", "$1000", "4 sahifa", ["Shaxsiy brend va kompaniya keysi", "Jamoa portreti", "Video intervyu va Reels / Shorts"]], ["04", "COVER STAR", "$2500", "muqova + 6 sahifa", ["Sonning asosiy yuzi", "Bosh hamkor maqomi", "To‘liq digital targ‘ibot"]]], selected: "Ko‘p tanlanadi",
        productionTitle: "Tahririyat ishlab chiqarishni o‘z zimmasiga oladi", production: [["Joyida suratga olish", "Jamoa sizning maydoningizda vizual ishlab chiqarishni tashkil etadi."], ["Jurnalist va tarjima", "Intervyu, tahrir va RU / UZ / EN moslashuvi."], ["Digital formatlar", "Portal, ijtimoiy tarmoqlar va qisqa videolar uchun materiallar."], ["VIP tarqatish", "Biznes va institutsional muhitda manzilli tarqatish."]],
        stepsTitle: "G‘oyadan songacha", steps: [["01", "Formatni tanlash"], ["02", "Konsepsiyani kelishish"], ["03", "Intervyu va ishlab chiqarish"], ["04", "Tahrir va komplaens"], ["05", "Chop etish, tarqatish va digital reliz"]]
      },
      en: {
        kicker: "BUSINESS HOLISTIC JOURNAL", title: "Your experience is read where decisions are made", lead: "An international research and business journal with targeted distribution in VIP trains, airports, ministries, embassies and banks.", issue: "ISSUE № 01", issueText: "Leadership expertise, business cases and ideas shaping the business agenda of Central Asia.", reserve: "Reserve a publication",
        formatsTitle: "Four formats of presence", formats: [["01", "EXPERT COLUMN", "$300", "1 page", ["Leader photoshoot", "Journalist support", "Full distribution network"]], ["02", "SUCCESS STORY", "$550", "2-page spread", ["In-depth interview", "Brand story and 2–3 images", "Website and LinkedIn publication"]], ["03", "BUSINESS ECOSYSTEM", "$1000", "4 pages", ["Leader brand and company case", "Team portrait", "Video interview and Reels / Shorts"]], ["04", "COVER STAR", "$2500", "cover + 6 pages", ["Main face of the issue", "General partner status", "Full digital promotion"]]], selected: "Most selected",
        productionTitle: "The editorial team handles production", production: [["On-location shoot", "The team organises visual production at your location."], ["Journalist and translation", "Interview, editing and RU / UZ / EN adaptation."], ["Digital formats", "Assets for the portal, social channels and short-form video."], ["VIP distribution", "Targeted reach across business and institutional environments."]],
        stepsTitle: "From idea to release", steps: [["01", "Choose format"], ["02", "Approve concept"], ["03", "Interview and production"], ["04", "Editing and compliance"], ["05", "Print, distribution and digital release"]]
      }
    },
    conferences: {
      ru: {
        kicker: "ЕЖЕГОДНЫЙ МЕЖДУНАРОДНЫЙ ФОРУМ", title: "Конференции, после которых начинаются партнёрства", lead: "BUSINESS HOLISTIC — институциональная площадка, где встречаются лидеры бизнеса и государства, C-level команды и международные эксперты.", stats: [["4", "конференции проведено"], ["18", "стран в 2025 году"], ["29", "спикеров в 2025 году"]], chronology: "Хронология", events: [["2023", "Открытие ассоциации", "Первая большая встреча HRBPA: 250 участников из пяти стран.", "assets/conference-2023.webp"], ["2024", "UNITE EVERYONE", "Экологические практики, человеческий капитал и новая культура сотрудничества.", "assets/conference-2024.webp"], ["2025", "Доверие как основа успеха", "327 участников, 29 спикеров и делегации из 13 стран.", "assets/conference-2025.webp"], ["2027", "Следующая орбита", "Новый масштаб международного диалога и практических партнёрств.", "assets/conference-2027.webp"]],
        meetingsTitle: "Формат работает круглый год", meetings: [["ЯНВ · 2024", "Круглый стол", "57 участников · 3 страны"], ["ФЕВ · 2024", "Дуальное образование", "280 участников · 9 стран"], ["ВЕСЬ ГОД", "Закрытые диалоги", "Отраслевые встречи и партнёрские сессии"]], ctaTitle: "Выйти на сцену или стать партнёром", ctaText: "Расскажите, какую экспертизу или ресурс вы хотите привнести в следующую конференцию."
      },
      uz: {
        kicker: "YILLIK XALQARO FORUM", title: "Hamkorlik boshlanadigan konferensiyalar", lead: "BUSINESS HOLISTIC — biznes va davlat yetakchilari, C-level jamoalar va xalqaro ekspertlar uchrashadigan institutsional maydon.", stats: [["4", "o‘tkazilgan konferensiya"], ["18", "2025-yildagi davlat"], ["29", "2025-yildagi spiker"]], chronology: "Xronologiya", events: [["2023", "Assotsiatsiya ochilishi", "HRBPAning birinchi yirik uchrashuvi: besh davlatdan 250 ishtirokchi.", "assets/conference-2023.webp"], ["2024", "UNITE EVERYONE", "Ekologik amaliyotlar, inson kapitali va yangi hamkorlik madaniyati.", "assets/conference-2024.webp"], ["2025", "Ishonch — muvaffaqiyat asosi", "327 ishtirokchi, 29 spiker va 13 davlat delegatsiyalari.", "assets/conference-2025.webp"], ["2027", "Keyingi orbita", "Xalqaro muloqot va amaliy hamkorlikning yangi ko‘lami.", "assets/conference-2027.webp"]],
        meetingsTitle: "Format yil davomida ishlaydi", meetings: [["YAN · 2024", "Davra suhbati", "57 ishtirokchi · 3 davlat"], ["FEV · 2024", "Dual ta’lim", "280 ishtirokchi · 9 davlat"], ["YIL DAVOMIDA", "Yopiq dialoglar", "Soha uchrashuvlari va hamkorlik sessiyalari"]], ctaTitle: "Sahnaga chiqing yoki hamkor bo‘ling", ctaText: "Keyingi konferensiyaga qanday ekspertiza yoki resurs olib kirishingizni ayting."
      },
      en: {
        kicker: "ANNUAL INTERNATIONAL FORUM", title: "Conferences where partnerships begin", lead: "BUSINESS HOLISTIC is an institutional platform connecting business and government leaders, C-level teams and international experts.", stats: [["4", "conferences held"], ["18", "countries in 2025"], ["29", "speakers in 2025"]], chronology: "Chronology", events: [["2023", "Association launch", "HRBPA’s first major gathering: 250 participants from five countries.", "assets/conference-2023.webp"], ["2024", "UNITE EVERYONE", "Environmental practices, human capital and a new culture of collaboration.", "assets/conference-2024.webp"], ["2025", "Trust as the foundation of success", "327 participants, 29 speakers and delegations from 13 countries.", "assets/conference-2025.webp"], ["2027", "The next orbit", "A new scale of international dialogue and practical partnerships.", "assets/conference-2027.webp"]],
        meetingsTitle: "The format works year-round", meetings: [["JAN · 2024", "Round table", "57 participants · 3 countries"], ["FEB · 2024", "Dual education", "280 participants · 9 countries"], ["YEAR-ROUND", "Private dialogues", "Industry meetings and partner sessions"]], ctaTitle: "Take the stage or become a partner", ctaText: "Tell us what expertise or resource you want to bring to the next conference."
      }
    },
    partners: {
      ru: {
        kicker: "РЕЗИДЕНТЫ & ПАРТНЁРЫ", title: "Не список логотипов, а действующая деловая экосистема", lead: "Компании, международные организации, эксперты и медиа объединяются вокруг доверия, человеческого капитала и практических совместных проектов.", stats: [["85", "организаций в сети"], ["14", "регионов Узбекистана"], ["1", "единая платформа"]], networkTitle: "В одной орбите", networkLead: "Участники работают в разных отраслях, но говорят на общем языке профессиональной репутации.", labels: ["EUROPOL", "GIZ", "USAID", "PARFUM GALLERY", "UZBEKISTAN MANAGERS ASSOCIATION", "OCA MAGAZINE", "SILK ROAD MEDIA", "JARVIX"],
        modesTitle: "Как строится партнёрство", modes: [["01", "Содержание", "Экспертиза, исследования, выступления и прикладные разборы."], ["02", "События", "Совместные конференции, закрытые встречи и отраслевые диалоги."], ["03", "Медиа", "Истории лидеров, кейсы компаний и международное информационное присутствие."], ["04", "Проекты", "Инициативы, которые соединяют бизнес, государство и профессиональное сообщество."]], ctaTitle: "Добавьте свою компетенцию в экосистему", ctaText: "Предложите партнёрство, спецпроект или отраслевую инициативу."
      },
      uz: {
        kicker: "REZIDENTLAR & HAMKORLAR", title: "Logotiplar ro‘yxati emas, ishlaydigan biznes ekotizimi", lead: "Kompaniyalar, xalqaro tashkilotlar, ekspertlar va media ishonch, inson kapitali va amaliy qo‘shma loyihalar atrofida birlashadi.", stats: [["85", "tarmoqdagi tashkilot"], ["14", "O‘zbekiston hududi"], ["1", "yagona platforma"]], networkTitle: "Bir orbitada", networkLead: "Ishtirokchilar turli sohalarda ishlaydi, ammo professional obro‘ning umumiy tilida gaplashadi.", labels: ["EUROPOL", "GIZ", "USAID", "PARFUM GALLERY", "UZBEKISTAN MANAGERS ASSOCIATION", "OCA MAGAZINE", "SILK ROAD MEDIA", "JARVIX"],
        modesTitle: "Hamkorlik qanday quriladi", modes: [["01", "Mazmun", "Ekspertiza, tadqiqot, chiqishlar va amaliy tahlillar."], ["02", "Tadbirlar", "Qo‘shma konferensiyalar, yopiq uchrashuvlar va soha dialoglari."], ["03", "Media", "Liderlar hikoyalari, kompaniya keyslari va xalqaro axborot ishtiroki."], ["04", "Loyihalar", "Biznes, davlat va professional hamjamiyatni bog‘laydigan tashabbuslar."]], ctaTitle: "Ekotizimga o‘z kompetensiyangizni qo‘shing", ctaText: "Hamkorlik, maxsus loyiha yoki soha tashabbusini taklif qiling."
      },
      en: {
        kicker: "RESIDENTS & PARTNERS", title: "Not a logo wall, but a working business ecosystem", lead: "Companies, international organisations, experts and media unite around trust, human capital and practical joint projects.", stats: [["85", "organisations in the network"], ["14", "regions of Uzbekistan"], ["1", "shared platform"]], networkTitle: "In one orbit", networkLead: "Members work across industries while speaking the common language of professional reputation.", labels: ["EUROPOL", "GIZ", "USAID", "PARFUM GALLERY", "UZBEKISTAN MANAGERS ASSOCIATION", "OCA MAGAZINE", "SILK ROAD MEDIA", "JARVIX"],
        modesTitle: "How partnership works", modes: [["01", "Content", "Expertise, research, talks and applied reviews."], ["02", "Events", "Joint conferences, private meetings and industry dialogues."], ["03", "Media", "Leader stories, company cases and international visibility."], ["04", "Projects", "Initiatives connecting business, government and the professional community."]], ctaTitle: "Add your expertise to the ecosystem", ctaText: "Propose a partnership, special project or industry initiative."
      }
    },
    contacts: {
      ru: {
        kicker: "КОНТАКТЫ", title: "Инициировать диалог", lead: "Выберите тему обращения — секретариат HRBPA ответит в течение рабочего дня и подключит нужного человека.", infoTitle: "Прямая связь", address: "Республика Узбекистан, Ташкент, 100085", formTitle: "Расскажите, с чего начнём", audience: "Профиль обращения", options: ["Ещё не определился", "Стать резидентом", "Участие в конференции", "Инвестор / спонсор", "Публикация в журнале", "Партнёрский проект"], name: "Имя и фамилия", company: "Компания и должность", phone: "Телефон · Telegram", email: "Email", message: "Сообщение", send: "Отправить запрос", note: "После нажатия откроется ваш почтовый клиент с заполненным письмом.", mapTitle: "Как нас найти", mapText: "Ташкент — точка сборки международного делового сообщества HRBPA.", mapLink: "Открыть на карте"
      },
      uz: {
        kicker: "BOG‘LANISH", title: "Muloqotni boshlang", lead: "Murojaat mavzusini tanlang — HRBPA kotibiyati bir ish kuni ichida javob beradi va kerakli mutaxassisni ulaydi.", infoTitle: "To‘g‘ridan-to‘g‘ri aloqa", address: "O‘zbekiston Respublikasi, Toshkent, 100085", formTitle: "Nimadan boshlashimizni ayting", audience: "Murojaat profili", options: ["Hali aniqlamadim", "Rezident bo‘lish", "Konferensiyada ishtirok", "Investor / homiy", "Jurnalda nashr", "Hamkorlik loyihasi"], name: "Ism va familiya", company: "Kompaniya va lavozim", phone: "Telefon · Telegram", email: "Email", message: "Xabar", send: "So‘rov yuborish", note: "Tugmani bosgandan so‘ng tayyor xat bilan pochta dasturingiz ochiladi.", mapTitle: "Bizni qanday topish mumkin", mapText: "Toshkent — HRBPA xalqaro biznes hamjamiyatining yig‘ilish nuqtasi.", mapLink: "Xaritada ochish"
      },
      en: {
        kicker: "CONTACTS", title: "Start a dialogue", lead: "Choose your subject and the HRBPA Secretariat will respond within one business day and connect the right person.", infoTitle: "Direct contact", address: "Republic of Uzbekistan, Tashkent, 100085", formTitle: "Tell us where to begin", audience: "Enquiry profile", options: ["Not decided yet", "Become a resident", "Conference participation", "Investor / sponsor", "Journal publication", "Partner project"], name: "Full name", company: "Company and title", phone: "Phone · Telegram", email: "Email", message: "Message", send: "Send request", note: "Your email client will open with a prepared message after you submit.", mapTitle: "How to find us", mapText: "Tashkent is the meeting point for HRBPA’s international business community.", mapLink: "Open map"
      }
    }
  };

  const nav = [
    ["about", "about.html"], ["residency", "residency.html"], ["journal", "journal.html"],
    ["conferences", "conferences.html"], ["partners", "partners.html"], ["contacts", "contacts.html"]
  ];

  const headerTemplate = (s) => `
    <a class="brand" href="index.html" aria-label="HRBPA — ${s.backHome}"><img src="assets/logo-hrbpa-white.svg" alt="" width="136" height="50" /></a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span></span><span></span><span></span><b>${s.menu}</b></button>
    <nav class="main-nav" id="main-nav" aria-label="${s.navigation}">${nav.map(([key, href]) => `<a href="${href}"${key === page ? ' class="is-active" aria-current="page"' : ""}>${s[key]}</a>`).join("")}</nav>
    <div class="header-actions"><div class="language-switcher" aria-label="Language">${["ru", "uz", "en"].map((code) => `<button class="${code === lang ? "is-active" : ""}" type="button" data-lang="${code}">${code.toUpperCase()}</button>`).join("")}</div><a class="header-cta" href="residency.html#apply">${s.join}</a></div>`;

  const footerTemplate = (s) => `
    <div class="footer-hero"><div class="footer-brand"><img src="assets/logo-hrbpa-white.svg" alt="HR Business Partners Association" width="280" height="102" /><p>${s.addressShort}</p></div><div class="footer-cta"><p>${s.joinText}</p><a class="button" href="residency.html#apply">${s.join}</a></div></div>
    <div class="footer-main">
      <section class="footer-column footer-contact"><h2>${s.contactTitle}</h2><address><span>${s.addressShort.replaceAll(" · ", "<br />")}</span><a href="tel:+998977022888">+998 97 702 28 88</a><a href="mailto:bilalova@bcguz.com">bilalova@bcguz.com</a></address></section>
      <nav class="footer-column footer-navigation" aria-label="${s.navigation}"><h2>${s.navigation}</h2>${nav.map(([key, href]) => `<a href="${href}">${s[key]}</a>`).join("")}</nav>
      <section class="footer-column footer-social"><h2>${s.social}</h2><a href="https://t.me/hrbpauz" target="_blank" rel="noreferrer">Telegram <span>↗</span></a><a href="https://www.instagram.com/hrbpa.uz/" target="_blank" rel="noreferrer">Instagram · HRBPA <span>↗</span></a><a href="https://www.instagram.com/business.holistic/" target="_blank" rel="noreferrer">Instagram · BUSINESS HOLISTIC <span>↗</span></a><a href="https://www.facebook.com/hrbpa.uz/" target="_blank" rel="noreferrer">Facebook <span>↗</span></a><a href="https://www.youtube.com/@business.holistic" target="_blank" rel="noreferrer">YouTube <span>↗</span></a></section>
      <section class="footer-column footer-legal"><h2>${s.legal}</h2><a href="https://lex.uz/docs/2468216" target="_blank" rel="noreferrer"><b>ЗРУ-376</b><span>${s.lawSocial}</span><i>↗</i></a><a href="https://lex.uz/docs/4494873" target="_blank" rel="noreferrer"><b>ЗРУ-562</b><span>${s.lawEquality}</span><i>↗</i></a><a href="https://lex.uz/docs/10863" target="_blank" rel="noreferrer"><b>763-I</b><span>${s.lawNgo}</span><i>↗</i></a><a href="https://lex.uz/docs/8050774" target="_blank" rel="noreferrer"><b>УП-21</b><span>${s.strategy}</span><i>↗</i></a></section>
    </div>
    <div class="footer-partner"><span>${s.partnerText}</span><a href="https://bcguz.com" target="_blank" rel="noreferrer">BILALOVA C GROUP ↗</a></div>
    <div class="footer-data" id="footer-data"><h2>${s.dataTitle}</h2><div><p>${s.dataText}</p><p>${s.formText} <a href="mailto:bilalova@bcguz.com">bilalova@bcguz.com</a>.</p></div></div>
    <div class="footer-bottom"><span>© 2026 HRBPA</span><a href="https://www.google.com/maps?q=41.2995,69.2401" target="_blank" rel="noreferrer">41.2995° N · 69.2401° E ↗</a><a href="mailto:bilalova@bcguz.com?subject=HRBPA%20—%20personal%20data">${s.privacy}</a><a href="#footer-data">${s.siteData}</a><a href="https://hrbpa.org" target="_blank" rel="noreferrer">hrbpa.org ↗</a><span>${s.footerText}</span></div>`;

  const hero = (d, variant = "") => `
    <section class="inner-hero ${variant}"><div class="inner-hero-orbit" aria-hidden="true"></div><div class="inner-hero-copy reveal"><a class="inner-breadcrumb" href="index.html">HRBPA <span>↗</span></a><p class="inner-kicker">${d.kicker}</p><h1>${d.title}</h1><p class="inner-lead">${d.lead}</p></div>${d.stats ? `<div class="inner-hero-stats">${d.stats.map(([value, label]) => `<div><strong>${value}</strong><span>${label}</span></div>`).join("")}</div>` : ""}</section>`;
  const heading = (index, title, lead = "") => `<div class="inner-section-head reveal"><span>${index}</span><div><h2>${title}</h2>${lead ? `<p>${lead}</p>` : ""}</div></div>`;

  const renderAbout = (d) => `${hero(d, "inner-hero--about")}
    <section class="inner-section inner-section--paper">${heading("01", d.trustTitle, d.trustLead)}<div class="pillar-grid">${d.pillars.map(([no, title, text]) => `<article class="pillar-card reveal"><span>${no}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    <section class="inner-section inner-section--ink">${heading("02", d.benefitsTitle)}<div class="benefit-grid">${d.benefits.map(([title, text], index) => `<article class="benefit-card reveal"><span>0${index + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    <section class="inner-section inner-section--paper">${heading("03", d.timelineTitle)}<div class="history-line">${d.timeline.map(([year, text]) => `<article class="history-item reveal"><strong>${year}</strong><p>${text}</p></article>`).join("")}</div></section>
    <section class="inner-section inner-section--cyan">${heading("04", d.directionsTitle)}<div class="direction-grid">${d.directions.map(([title, text]) => `<article class="direction-card reveal"><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    <section class="founder-section"><div class="founder-image reveal"><img src="assets/madina-bilalova.webp" alt="${d.founderName}" /></div><div class="founder-copy reveal"><p class="inner-kicker">${d.founderTitle}</p><h2>${d.founderName}</h2><p>${d.founderText}</p><a class="button button--light" href="contacts.html">${shared[lang].discuss}</a></div></section>`;

  const renderResidency = (d) => `${hero({ ...d, stats: [["03", d.tiersTitle], ["09", d.badge], ["365", d.perYear]] }, "inner-hero--residency")}
    <section class="inner-section inner-section--paper"><div class="access-groups">${d.groups.map(([group, items], groupIndex) => `<section class="access-group reveal"><span>0${groupIndex + 1}</span><h2>${group}</h2>${items.map(([title, text]) => `<article><h3>${title}</h3><p>${text}</p></article>`).join("")}</section>`).join("")}</div></section>
    <section class="inner-section inner-section--ink" id="levels">${heading("02", d.tiersTitle)}<div class="inner-tier-grid">${d.tiers.map(([name, price, brv, items], index) => `<article class="inner-tier ${index === 1 ? "is-featured" : ""} reveal">${index === 1 ? `<b>${d.featured}</b>` : ""}<span>0${index + 1}</span><h3>${name}</h3><strong>${price}</strong><small>${brv} · ${d.perYear}</small><ul>${items.map((item) => `<li>${item}</li>`).join("")}</ul><a class="button ${index === 1 ? "button--dark" : "button--light"}" href="contacts.html?topic=${name.toLowerCase()}">${d.choose}</a></article>`).join("")}</div></section>
    <section class="inner-section inner-section--paper">${heading("03", d.stepsTitle)}<div class="step-line">${d.steps.map(([no, title, text]) => `<article class="step-card reveal"><strong>${no}</strong><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    ${ctaBlock(d.ctaTitle, d.ctaText, shared[lang].apply, "contacts.html?topic=residency", "apply")}`;

  const renderJournal = (d) => `<section class="journal-inner-hero"><div class="journal-inner-bg" aria-hidden="true"></div><div class="journal-inner-copy reveal"><p class="inner-kicker">${d.kicker}</p><h1>${d.title}</h1><p>${d.lead}</p><a class="button button--light" href="#formats">${d.reserve}</a></div><div class="journal-inner-issue reveal"><div class="journal-halo"></div><img src="assets/journal-issue-01.webp" alt="${d.issue}" /><span>${d.issue}</span><p>${d.issueText}</p></div></section>
    <section class="inner-section inner-section--paper" id="formats">${heading("01", d.formatsTitle)}<div class="format-grid">${d.formats.map(([no, name, price, volume, items], index) => `<article class="format-card ${index === 2 ? "is-selected" : ""} reveal">${index === 2 ? `<b>${d.selected}</b>` : ""}<span>${no}</span><h3>${name}</h3><strong>${price}</strong><small>${volume}</small><ul>${items.map((item) => `<li>${item}</li>`).join("")}</ul><a href="contacts.html?topic=journal&format=${name.toLowerCase().replaceAll(" ", "-")}">${d.reserve} ↗</a></article>`).join("")}</div></section>
    <section class="inner-section inner-section--ink">${heading("02", d.productionTitle)}<div class="benefit-grid">${d.production.map(([title, text], index) => `<article class="benefit-card reveal"><span>0${index + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    <section class="inner-section inner-section--paper">${heading("03", d.stepsTitle)}<div class="journal-steps">${d.steps.map(([no, text]) => `<article class="reveal"><strong>${no}</strong><span>${text}</span></article>`).join("")}</div></section>`;

  const renderConferences = (d) => `${hero(d, "inner-hero--conference")}
    <section class="inner-section inner-section--blue">${heading("01", d.chronology)}<div class="conference-grid">${d.events.map(([year, title, text, image]) => `<article class="conference-card reveal"><div class="conference-card-image"><img src="${image}" alt="" /></div><div><strong>${year}</strong><h3>${title}</h3><p>${text}</p></div></article>`).join("")}</div></section>
    <section class="inner-section inner-section--paper">${heading("02", d.meetingsTitle)}<div class="meeting-grid">${d.meetings.map(([date, title, text]) => `<article class="reveal"><span>${date}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    ${ctaBlock(d.ctaTitle, d.ctaText, shared[lang].discuss, "contacts.html?topic=conference")}`;

  const renderPartners = (d) => `${hero(d, "inner-hero--partners")}
    <section class="inner-section inner-section--paper">${heading("01", d.networkTitle, d.networkLead)}<div class="partner-directory">${d.labels.map((label, index) => `<div class="partner-mark reveal"><span>${String(index + 1).padStart(2, "0")}</span><strong>${label}</strong></div>`).join("")}</div></section>
    <div class="inner-marquee" aria-hidden="true"><div>${[...d.labels, ...d.labels].map((item) => `<span>${item}</span>`).join("")}</div></div>
    <section class="inner-section inner-section--ink">${heading("02", d.modesTitle)}<div class="benefit-grid">${d.modes.map(([no, title, text]) => `<article class="benefit-card reveal"><span>${no}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section>
    ${ctaBlock(d.ctaTitle, d.ctaText, shared[lang].discuss, "contacts.html?topic=partnership")}`;

  const renderContacts = (d) => `${hero({ ...d, stats: undefined }, "inner-hero--contacts")}
    <section class="contact-inner-section"><aside class="contact-panel reveal"><p class="inner-kicker">${d.infoTitle}</p><h2>HRBPA</h2><address><span>${d.address}</span><a href="tel:+998977022888">+998 97 702 28 88</a><a href="mailto:bilalova@bcguz.com">bilalova@bcguz.com</a></address><div class="contact-social"><a href="https://t.me/hrbpauz" target="_blank" rel="noreferrer">Telegram ↗</a><a href="https://www.instagram.com/hrbpa.uz/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.youtube.com/@business.holistic" target="_blank" rel="noreferrer">YouTube ↗</a></div></aside>
      <form class="inner-contact-form reveal" id="inner-contact-form"><h2>${d.formTitle}</h2><label><span>${d.audience}</span><select name="topic">${d.options.map((option) => `<option>${option}</option>`).join("")}</select></label><div class="form-pair"><label><span>${d.name}</span><input name="name" required autocomplete="name" /></label><label><span>${d.company}</span><input name="company" autocomplete="organization" /></label></div><div class="form-pair"><label><span>${d.phone}</span><input name="phone" required autocomplete="tel" placeholder="+998 __ ___ __ __" /></label><label><span>${d.email}</span><input name="email" required type="email" autocomplete="email" /></label></div><label><span>${d.message}</span><textarea name="message" rows="5"></textarea></label><button class="button button--dark" type="submit">${d.send}</button><p>${d.note}</p></form></section>
    <section class="map-panel"><div class="map-pulse" aria-hidden="true"><i></i><i></i><i></i><b></b></div><div class="reveal"><p class="inner-kicker">41.2995° N · 69.2401° E</p><h2>${d.mapTitle}</h2><p>${d.mapText}</p><a class="button button--light" href="https://www.google.com/maps?q=41.2995,69.2401" target="_blank" rel="noreferrer">${d.mapLink} ↗</a></div></section>`;

  function ctaBlock(title, text, label, href, id = "") {
    return `<section class="inner-cta"${id ? ` id="${id}"` : ""}><div class="reveal"><p>HRBPA · TASHKENT</p><h2>${title}</h2><span>${text}</span></div><a class="button button--light" href="${href}">${label} ↗</a></section>`;
  }

  const renderers = { about: renderAbout, residency: renderResidency, journal: renderJournal, conferences: renderConferences, partners: renderPartners, contacts: renderContacts };

  function setupInteractions() {
    const header = document.querySelector(".site-header");
    const menuToggle = document.querySelector(".menu-toggle");
    const menu = document.querySelector(".main-nav");
    const actions = document.querySelector(".header-actions");
    const close = () => { menuToggle.setAttribute("aria-expanded", "false"); menu.classList.remove("is-open"); actions.classList.remove("is-open"); header.classList.remove("menu-visible"); body.classList.remove("menu-open"); };
    menuToggle.addEventListener("click", () => { const open = menuToggle.getAttribute("aria-expanded") !== "true"; menuToggle.setAttribute("aria-expanded", String(open)); menu.classList.toggle("is-open", open); actions.classList.toggle("is-open", open); header.classList.toggle("menu-visible", open); body.classList.toggle("menu-open", open); });
    menu.querySelectorAll("a").forEach((link) => link.addEventListener("click", close));
    document.querySelectorAll("[data-lang]").forEach((button) => button.addEventListener("click", () => { lang = button.dataset.lang; localStorage.setItem("hrbpa-lang", lang); render(); }));
    const observer = "IntersectionObserver" in window && !reduceMotion ? new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12 }) : null;
    document.querySelectorAll(".reveal").forEach((element, index) => { element.style.transitionDelay = `${Math.min(index % 4, 3) * 60}ms`; if (observer) observer.observe(element); else element.classList.add("is-visible"); });
    const form = document.querySelector("#inner-contact-form");
    if (form) {
      const topic = new URLSearchParams(location.search).get("topic");
      if (topic) { const match = [...form.elements.topic.options].find((option) => option.textContent.toLowerCase().includes(topic.toLowerCase())); if (match) match.selected = true; }
      form.addEventListener("submit", (event) => { event.preventDefault(); const values = new FormData(form); const subject = `HRBPA — ${values.get("topic")}`; const message = [`${dForPage().name}: ${values.get("name")}`, `${dForPage().company}: ${values.get("company")}`, `${dForPage().phone}: ${values.get("phone")}`, `${dForPage().email}: ${values.get("email")}`, "", values.get("message")].join("\n"); window.location.href = `mailto:bilalova@bcguz.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`; });
    }
  }

  function dForPage() { return pages[page][lang] || pages[page].ru; }
  function render() {
    const s = shared[lang];
    const d = dForPage();
    root.lang = lang;
    document.title = `${d.kicker || s[page]} — HRBPA`;
    document.querySelector("#site-header").innerHTML = headerTemplate(s);
    document.querySelector("#main").innerHTML = renderers[page](d);
    document.querySelector("#site-footer").innerHTML = footerTemplate(s);
    setupInteractions();
  }

  const progress = document.querySelector(".scroll-progress");
  let ticking = false;
  const updateProgress = () => { const max = Math.max(1, document.documentElement.scrollHeight - innerHeight); progress.style.transform = `scaleX(${Math.min(1, scrollY / max)})`; ticking = false; };
  addEventListener("scroll", () => { if (!ticking) { requestAnimationFrame(updateProgress); ticking = true; } }, { passive: true });
  addEventListener("keydown", (event) => { if (event.key === "Escape") { document.querySelector(".menu-toggle")?.setAttribute("aria-expanded", "false"); document.querySelector(".main-nav")?.classList.remove("is-open"); document.querySelector(".header-actions")?.classList.remove("is-open"); body.classList.remove("menu-open"); } });
  render();
  updateProgress();
})();
